---
title: "ctrest"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ctrest}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## パッケージの概要/Package Overview

　"ctrest"は，RESTモデルもしくはREST-RADモデルを簡単に利用するためのRパッケージです．

REST/REST-RADモデルとは，自動撮影カメラ（カメラトラップ）によって得られた動画データに基づいて地上性哺乳類・鳥類の密度推定を行うための統計モデルです．RESTモデルの詳細について[Nakashima et al. (2018)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.13059)，REST-RADモデルについてはXXXXXX（執筆中）をご参照ください．また，データの準備までのプロセスについては，[Nakashima et al. (2021)](https://www.biorxiv.org/content/10.1101/2021.05.18.444583v2)を参照してください．

　パッケージは，以下のような関数を含みます．

-   **データの前処理**：必要なデータの前処理を行います．後で使う密度推定用の関数は，これらの関数を利用して前処理を行ったこと（もしくは，それと同じ列名を持つデータであること）を前提に作られています（引数指定の数を出来るだけ減らすため）．

-   **密度推定：**推定手法によって異なる関数を定義しています．

    -   **最尤法**：**mle_rest関数**は，最尤法に基づいてパラメータ推定を行います．この関数は，地点全体の平均的な密度を推定する場合のみに対応しています（滞在時間や密度のパラメータに共変量やランダム効果を含めることはできません）．

    -   **ベイズ法**：**bayes_rest関数**は，ベイズ法に基づいてパラメータ推定を行います．より発展的な解析を行うのに適しています．Nimbleを用いたMCMC法を利用しています．

"ctrest" is an R package designed to facilitate the use of REST models or REST-RAD models. REST/REST-RAD models are statistical models for estimating the density of ground-dwelling mammals and birds based on video data obtained from camera traps. For details on the REST model, please refer to [Nakashima et al. (2018)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.13059), and for the REST-RAD model, please refer to XXXXXX. For the data preparation process, please refer to [Nakashima et al. (2021)](https://www.biorxiv.org/content/10.1101/2021.05.18.444583v2). The package includes the following functions:

-   **Data preprocessing**: Performs necessary data preprocessing. The density estimation functions that will be used later are designed assuming that preprocessing has been done using these functions (or that the data has the same column names) to minimize the number of argument specifications.

-   **Density estimation**: Different functions are defined based on the estimation method.

    -   **Maximum likelihood**: The mle_rest function performs parameter estimation based on maximum likelihood. This function only supports estimating the average density across all sites (covariates and random effects cannot be included in staying time or density parameters).

    -   **Bayesian method**: The bayes_rest function performs parameter estimation based on Bayesian methods. It is suitable for more advanced analyses. It uses MCMC methods implemented in Nimble.
